# settings.yaml
# box_name: "sloopstash/ubuntu-22-04"
box_name: "bento/ubuntu-22.04"
# box_name: "starboard/ubuntu-arm64-20.04.5"
# box_version: "20221120.20.40.0"
vm:
- name: "operator"
  ip: "192.168.201.9"
  memory: "2048"
  cpus: "2"
- name: "controlplane"
  ip: "192.168.201.10"
  memory: "2048"
  cpus: "2"
- name: "node01"
  ip: "192.168.201.11"
  memory: "2048"
  cpus: "2"
- name: "node02"
  ip: "192.168.201.12"
  memory: "2048"
  cpus: "2"
